//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amonic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аэропорты
    {
        public string Код_Аэропорта { get; set; }
        public string Страна { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public string Строение { get; set; }
    }
}
