//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amonic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Билеты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Билеты()
        {
            this.Оформление_билетов = new HashSet<Оформление_билетов>();
        }
    
        public int Код_билета { get; set; }
        public int Номер_рейса { get; set; }
        public Nullable<int> Номер_обратного_рейса { get; set; }
        public System.DateTime Дата_полета { get; set; }
        public Nullable<System.DateTime> Дата_обратного_полета { get; set; }
    
        public virtual Рейсы Рейсы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оформление_билетов> Оформление_билетов { get; set; }
    }
}
