//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amonic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Информация_о_пользователе
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Информация_о_пользователе()
        {
            this.Попытки_входа = new HashSet<Попытки_входа>();
        }
    
        public int id_пользователя { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Активность { get; set; }
        public bool Права_администратора { get; set; }
        public int id_офиса { get; set; }
    
        public virtual Офисы Офисы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Попытки_входа> Попытки_входа { get; set; }
    }
}
