//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amonic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рейсы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Рейсы()
        {
            this.Билеты = new HashSet<Билеты>();
        }
    
        public int Номер_рейса { get; set; }
        public System.DateTime Дата_вылета { get; set; }
        public System.TimeSpan Время_вылета { get; set; }
        public decimal Цена { get; set; }
        public string Подтверждение { get; set; }
        public int id_Самолета { get; set; }
        public string Код_аэропорта { get; set; }
        public string Код_аэропорта_посадки { get; set; }
        public Nullable<decimal> Бизнесс_цена { get; set; }
        public Nullable<decimal> Первый_класс_цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Билеты> Билеты { get; set; }
        public virtual Самолеты Самолеты { get; set; }
    }
}
